### ISSUE TITLE
Fix: Magic Bounty 5000 USD instead of 35000 USD.

### ISSUE THREAD

**Issue by 0xlxy** [AleksanderMisztal/ethdenverbounties#3]
According to this [source](https://app.buidlbox.io/ethdenver/ethdenver-2023): the total bounty from the Magic Wallet SDK is 5K USD total, not 35K USD.
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/72717104/221344006-90255b0e-e8e7-4b56-80fa-a16ba73f3a2e.png">

**Comment by AleksanderMisztal** [comment]
Thanks! Fixed now.
